version: '2'
services:
  clase31ago-app:
    image: clase31ago
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://clase31ago-postgresql:5432/clase31Ago
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8099:8099
  clase31ago-postgresql:
    extends:
      file: postgresql.yml
      service: clase31ago-postgresql
